### ISSUE TITLE
cannot run main script

### ISSUE THREAD

**Issue by disfinder** [stas-udav/amazon_scraping#2]
gives an error

```shell
$ python ./amazon_scraper.py
Traceback (most recent call last):
  File "amazon_scraping/./amazon_scraper.py", line 12, in <module>
    import functions as func
  File "amazon_scraping/functions.py", line 3, in <module>
    from tkinter import simpledialog
  File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_tkinter'
```

**Comment by stas-udav** [comment]
added to requirements.txt
